language: node_js
node_js:
  - 'node'
  - '8'
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "pxr1fBfz8nD5mI71Ynb/beY0PTegx7o+gqaBw3kIGEQpuu5MNGmDDRZKyR4BOzyRDiuNn7dQ62AECdEgyiOX07tB3PF0/s5iVqX8aDGHo8UO9NY4IVGQLDaRWJrdz63wrALEzTpAKnRKpvpOTUkcy6QCX6c1cP9buHx+zP6etPq+P2fk8VwLRv69CN2FFLihNWsn5akijxe46slWFy7K6pJD3DeEayOUlNJQdniwMLw0Xi7fe+j4UcXRVBt30fO3s6OJKFOpha18oMjF+GWoGTB9ti+vA/bFDUHgKIbZDjqAkSN16L4hXoiBhOqPHDTEDbzMOWbDaZAYZbJlEm12MCO7OueJMtyssdLPQzdXue/ev/IcT3oT2SLKp9Hqk43u14xh5sgmBv1vf2TrTZU9PYd32ssPIATHE2/mMkv71dJbCdGlFViAxeGZI4ERDAx/9ys6BPoCMON6kfvXsPyPXUHLOYgGSvPNs53WmfhxDozMKcAtXa+Tib/Y0HZUmkVH/bpzaO+1xCEgBCATWU7x6FSrlI1f8oJcMNNaepGjtEWSJo13rKOMV7/xmAAx/KnrfX+S1nxd75h78VQWZD5NFqfb/Gg5MXUeZ5QEGUP1kxCC8sKvaG4pFW/HQIA1WLXozTCohOQgwWaV5CKqrnkZC5wuTGZ7BSaxmR7VpFgROT4="
