language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "R+XgfmJn07oATPdf0IL15u5cTISTCtRSUeKamevR5OJ4Q4SmcUinyIb8q5UC7ipYmcLclw7UqchByS+Ca0wTH5MbrPl/pk9hLAPIrgTiZhO837Io0L2Hg8De/iH97MWCNJQYyWsagy0K7eVaOxnAz0jYqFP/Fb2YHc2Sa+6b29gMpa/t/amC6fsOzHTJYcCMOc9gBEQkYPs9M7qwfQzEYTbHT/1uZsvIy/cPNi5RcyCVLgnRbd2qIWZfRgIYn+Y7QCuOCC4PeP0B1Y1lAnh3z0ZQpBIDurGtzcyUv9dH8SLOm6pk0KvObotvLugbwCSNb7WWrCq+FFysvGaJxHYyhPUyKxybIG24Y/ha0Tje+TbpkqtU0/+caiTsis9tF0OPMsoZhdYYHZP4q3vxDDAcaEFjkxEfdSrhrf70Ow04wZCYRzuQkNuEw5pVfqjkvVe3nkYqSreLxX2msCnoohw0/LNm8PoF/f67SvZiBk3Pw1wZnitxQdGT9yv2wbJTrrQM3aQ2QDkJDH7yG9eJE8YW2DP1ZfSF46H30LoqcXIPQ/EuiF5NbLOi55kK9pm38eAGKEflhKHEr6ZX0F47pzQgVN2RDAEBbBfKirukgfcAXM1jeIEuO7PbrXnfUoaBhhlL2jDNer6hM/pilIASTBarwHXWT/QzFSqCa+Cm2CFll1c="
